services:
  dev:
    image: ${REPO:-gardenio}/${IMAGE}:latest
    container_name: ${IMAGE}
    volumes:
      - ../..:/workspace
    networks:
      - gardenflow-dev-stack

  postgis:
    image: postgis/postgis:17-3.5
    container_name: ${IMAGE}-postgis
    platform: linux/amd64
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    networks:
      gardenflow-dev-stack:
        aliases:
          - postgis
    volumes:
      - postgis_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ${IMAGE}-redis
    ports:
      - "6379:6379"
    networks:
      gardenflow-dev-stack:
        aliases:
          - redis

volumes:
  postgis_data:

networks:
  gardenflow-dev-stack:
    name: gardenflow-dev-stack
